LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := SystemUIGoogleParasite
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := SystemUIGoogle.apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_CLASS := APPS
LOCAL_SYSTEM_EXT_MODULE := true
LOCAL_PRIVILEGED_MODULE := true
LOCAL_MODULE_RELATIVE_PATH := SystemUIGoogle
LOCAL_OPTIONAL_USES_LIBRARIES := androidx.window.extensions androidx.window.sidecar
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_NO_STANDARD_LIBRARIES := true
LOCAL_OVERRIDES_PACKAGES := SystemUI SystemUIGoogle
LOCAL_MULTILIB := both
include $(BUILD_PREBUILT)
