# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/google/pixel-framework/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/google/pixel-framework/common


PRODUCT_PACKAGES += \
    SettingsGoogle \
    SystemUIGoogle
