# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/google/pixel-framework/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/google/pixel-framework/common

PRODUCT_COPY_FILES += \
    vendor/google/pixel-framework/common/proprietary/system_ext/etc/permissions/com.google.android.settings.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.google.android.settings.xml \
    vendor/google/pixel-framework/common/proprietary/system_ext/etc/permissions/com.google.android.systemui.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.google.android.systemui.xml
